import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Banner from "../components/Banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import dynamic from "next/dynamic";
import { draftMode } from "next/headers";
import { token } from "../../sanity/lib/fetch";

const PreviewProvider = dynamic(() => import("../components/PreviewProvider"));

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Banner />
        {draftMode().isEnabled ? (
          <PreviewProvider token={token}>{children}</PreviewProvider>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  );
}
